/**
 * FreeIMU calibration header. Automatically generated by octave CompassCalib.m.
 * Do not edit manually unless you know what you are doing.
*/

//originals

const int acc_off_x = -122;
const int acc_off_y = -50;
const int acc_off_z = 1899;
const float acc_scale_x = 7854.214369;
const float acc_scale_y = 8289.764198;
const float acc_scale_z = 8502.598820;



//originals
const int magn_off_x = 62;
const int magn_off_y = -34;
const int magn_off_z = 18;
const float magn_scale_x = 527.774875;
const float magn_scale_y = 539.364299;
const float magn_scale_z = 499.251625;


/*
//my values 15.9.2012 Timok
const int magn_off_x = 65;
const int magn_off_y = -134;
const int magn_off_z = 35;
const float magn_scale_x = 502.080584;
const float magn_scale_y = 507.075445;
const float magn_scale_z = 464.021794;
*/


//values measured 17.9 2012 Timok
/*
const int magn_off_x = 68;
const int magn_off_y = -130;
const int magn_off_z = 29;
const int magn_scale_x = 456.450972;
const int magn_scale_y = 486.129150;
const int magn_scale_z = 438.127300;
*/

/*
//values measured 17.9 2012 Timok
const int acc_off_x = -67;
const int acc_off_y = 31;
const int acc_off_z = -1013;
const int acc_scale_x = 15218.079572;
const int acc_scale_y = 16585.598253;
const int acc_scale_z = 16839.086501;
*/









